# Generated by Django 6.0 on 2025-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("other", "Other"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Include country code, e.g. +1 555-123-4567",
                        max_length=30,
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("facebook", "Facebook Messenger"),
                            ("sms", "SMS"),
                            ("phone", "Phone Call"),
                            ("other", "Other"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "income_scale",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Low income"),
                            (2, "2 - Below average"),
                            (3, "3 - Average"),
                            (4, "4 - Above average"),
                            (5, "5 - High income"),
                        ],
                        default=3,
                        help_text="Estimated income level 1-5",
                    ),
                ),
                (
                    "donation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total donation amount in USD",
                        max_digits=10,
                    ),
                ),
                ("donation_date", models.DateField(blank=True, null=True)),
                (
                    "has_shared",
                    models.BooleanField(
                        default=False, help_text="Has shared the fundraiser post"
                    ),
                ),
                ("share_date", models.DateField(blank=True, null=True)),
                ("last_contacted", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this donor"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-donation_amount", "-created_at"],
            },
        ),
    ]
