# Generated by Django 6.0 on 2025-12-14 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CBPIAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worst_pain",
                    models.IntegerField(
                        help_text="Rate the pain at its worst in the last 7 days",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "least_pain",
                    models.IntegerField(
                        help_text="Rate the pain at its least in the last 7 days",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "average_pain",
                    models.IntegerField(
                        help_text="Rate the pain on average",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "current_pain",
                    models.IntegerField(
                        help_text="Rate the pain right now",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "general_activity",
                    models.IntegerField(
                        help_text="Interference with general activity",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "enjoyment_of_life",
                    models.IntegerField(
                        help_text="Interference with enjoyment of life",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "ability_to_rise",
                    models.IntegerField(
                        help_text="Interference with ability to rise to standing from lying down",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "ability_to_walk",
                    models.IntegerField(
                        help_text="Interference with walking",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "ability_to_run",
                    models.IntegerField(
                        help_text="Interference with running",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "ability_to_climb",
                    models.IntegerField(
                        help_text="Interference with climbing (stairs, curbs, etc.)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "overall_quality_of_life",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        help_text="Overall quality of life assessment",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CBPI Assessment",
                "verbose_name_plural": "CBPI Assessments",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CORQAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "energy_level",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog has normal energy levels",
                    ),
                ),
                (
                    "playfulness",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog is playful",
                    ),
                ),
                (
                    "interest_in_surroundings",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog shows interest in surroundings",
                    ),
                ),
                (
                    "appetite",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog has normal appetite",
                    ),
                ),
                (
                    "seeks_attention",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog seeks attention from family",
                    ),
                ),
                (
                    "enjoys_interaction",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog enjoys interaction with people",
                    ),
                ),
                (
                    "greets_family",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog greets family members",
                    ),
                ),
                (
                    "tail_wagging",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog wags tail",
                    ),
                ),
                (
                    "shows_pain",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog shows signs of pain",
                    ),
                ),
                (
                    "vocalizes_pain",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog vocalizes (whines, cries) due to pain",
                    ),
                ),
                (
                    "avoids_touch",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog avoids being touched",
                    ),
                ),
                (
                    "pants_restless",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog pants or is restless",
                    ),
                ),
                (
                    "walks_normally",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog walks normally",
                    ),
                ),
                (
                    "rises_easily",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog rises easily from lying down",
                    ),
                ),
                (
                    "climbs_stairs",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog can climb stairs",
                    ),
                ),
                (
                    "jumps",
                    models.IntegerField(
                        choices=[
                            (1, "Never"),
                            (2, "Rarely"),
                            (3, "Sometimes"),
                            (4, "Often"),
                            (5, "Always"),
                        ],
                        help_text="Dog can jump (on furniture, into car)",
                    ),
                ),
                (
                    "global_qol",
                    models.IntegerField(
                        help_text="Overall quality of life (0-100 visual analog scale)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CORQ Assessment",
                "verbose_name_plural": "CORQ Assessments",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("chemo", "Chemotherapy"),
                            ("radiation", "Radiation therapy"),
                            ("surgery", "Surgery"),
                            ("immunotherapy", "Immunotherapy"),
                            ("palliative", "Palliative care"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chop", "CHOP Protocol"),
                            ("cop", "COP Protocol"),
                            ("single_agent", "Single Agent"),
                            ("madison_wisconsin", "Madison-Wisconsin Protocol"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        blank=True,
                        help_text="Specific drug or agent used (e.g., Vincristine, Doxorubicin)",
                        max_length=100,
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        blank=True, help_text="Dose administered", max_length=50
                    ),
                ),
                (
                    "cycle_number",
                    models.IntegerField(
                        blank=True, help_text="Treatment cycle number", null=True
                    ),
                ),
                (
                    "pre_treatment_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg before treatment",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment Session",
                "verbose_name_plural": "Treatment Sessions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="VCOGCTCAEEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gastrointestinal", "Gastrointestinal"),
                            ("hematologic", "Hematologic/Blood"),
                            ("constitutional", "Constitutional Symptoms"),
                            ("dermatologic", "Dermatologic/Skin"),
                            ("neurologic", "Neurologic"),
                            ("cardiac", "Cardiac"),
                            ("respiratory", "Respiratory"),
                            ("renal", "Renal/Urinary"),
                            ("hepatic", "Hepatic"),
                            ("immunologic", "Immunologic"),
                            ("infection", "Infection"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("vomiting", "Vomiting"),
                            ("diarrhea", "Diarrhea"),
                            ("anorexia", "Anorexia/Decreased appetite"),
                            ("nausea", "Nausea"),
                            ("constipation", "Constipation"),
                            ("colitis", "Colitis"),
                            ("neutropenia", "Neutropenia"),
                            ("thrombocytopenia", "Thrombocytopenia"),
                            ("anemia", "Anemia"),
                            ("leukopenia", "Leukopenia"),
                            ("lethargy", "Lethargy/Fatigue"),
                            ("fever", "Fever"),
                            ("weight_loss", "Weight loss"),
                            ("alopecia", "Alopecia/Hair loss"),
                            ("dermatitis", "Dermatitis"),
                            ("pruritus", "Pruritus/Itching"),
                            ("infection", "Infection"),
                            ("hemorrhage", "Hemorrhage"),
                            ("pain", "Pain"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (1, "Grade 1 - Mild"),
                            (2, "Grade 2 - Moderate"),
                            (3, "Grade 3 - Severe"),
                            (4, "Grade 4 - Life-threatening"),
                            (5, "Grade 5 - Death"),
                        ]
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        blank=True,
                        help_text="Chemotherapy agent or treatment that may have caused this event",
                        max_length=100,
                    ),
                ),
                (
                    "intervention",
                    models.TextField(
                        blank=True,
                        help_text="Treatment or intervention for this adverse event",
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VCOG-CTCAE Event",
                "verbose_name_plural": "VCOG-CTCAE Events",
                "ordering": ["-date"],
            },
        ),
    ]
