# Generated by Django 6.0 on 2025-12-14 18:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_cbpiassessment_corqassessment_treatmentsession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("protein", "Protein"),
                            ("fat", "Fat/Oil"),
                            ("vegetable", "Vegetable"),
                            ("carb", "Carbohydrate"),
                            ("supplement", "Supplement"),
                            ("commercial", "Commercial Food"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("limited", "Limited Use"),
                            ("avoid", "Avoid"),
                            ("blocked", "Blocked - Do Not Use"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("calories_per_100g", models.IntegerField(blank=True, null=True)),
                (
                    "protein_g_per_100g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "fat_g_per_100g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "carbs_g_per_100g",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "epa_mg_per_100g",
                    models.IntegerField(
                        blank=True, help_text="EPA omega-3 in mg", null=True
                    ),
                ),
                (
                    "dha_mg_per_100g",
                    models.IntegerField(
                        blank=True, help_text="DHA omega-3 in mg", null=True
                    ),
                ),
                ("calcium_mg_per_100g", models.IntegerField(blank=True, null=True)),
                (
                    "max_per_day",
                    models.CharField(
                        blank=True,
                        help_text="Maximum recommended per day (e.g., '2 eggs', '3 meals/week')",
                        max_length=100,
                    ),
                ),
                (
                    "max_per_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum servings per week (for limited foods)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "warning",
                    models.TextField(
                        blank=True,
                        help_text="Warning message if status is limited/avoid",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyNutritionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_food_g", models.IntegerField(default=0)),
                (
                    "total_protein_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_fat_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_carbs_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("total_calcium_mg", models.IntegerField(default=0)),
                ("total_omega3_mg", models.IntegerField(default=0)),
                ("multivitamin_given", models.BooleanField(default=False)),
                ("meals_count", models.IntegerField(default=0)),
                ("eggs_count", models.IntegerField(default=0)),
                ("tuna_servings", models.IntegerField(default=0)),
                ("carbs_warning", models.BooleanField(default=False)),
                ("calcium_low", models.BooleanField(default=False)),
                ("omega3_low", models.BooleanField(default=False)),
                ("food_low", models.BooleanField(default=False)),
                ("eggs_warning", models.BooleanField(default=False)),
                ("tuna_warning", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Nutrition Summary",
                "verbose_name_plural": "Daily Nutrition Summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DogProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Bruno", max_length=100)),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current weight in kilograms",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "target_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target/ideal weight in kilograms",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appetite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent - Ate eagerly"),
                            ("good", "Good - Ate well"),
                            ("fair", "Fair - Ate some"),
                            ("poor", "Poor - Barely ate"),
                            ("refused", "Refused to eat"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hand_fed",
                    models.BooleanField(default=False, help_text="Food was hand-fed"),
                ),
                (
                    "warmed",
                    models.BooleanField(
                        default=False, help_text="Food was warmed to enhance smell"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="MealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_food_name",
                    models.CharField(
                        blank=True, help_text="If food not in database", max_length=100
                    ),
                ),
                ("amount_g", models.IntegerField(help_text="Amount in grams")),
                (
                    "amount_display",
                    models.CharField(
                        blank=True,
                        help_text="Human readable amount (e.g., '2 eggs', '1 cup')",
                        max_length=50,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="health.food",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="health.meal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplementDose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "supplement_type",
                    models.CharField(
                        choices=[
                            ("calcium", "Calcium"),
                            ("fish_oil", "Fish Oil (Omega-3)"),
                            ("multivitamin", "Multivitamin"),
                            ("vitamin_e", "Vitamin E"),
                            ("vitamin_b", "B-Complex"),
                            ("probiotic", "Probiotic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                (
                    "dose_amount",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '1 tsp', '2 capsules', '1000 mg'",
                        max_length=50,
                    ),
                ),
                ("calcium_mg", models.IntegerField(blank=True, null=True)),
                ("epa_mg", models.IntegerField(blank=True, null=True)),
                ("dha_mg", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "supplement_type"],
            },
        ),
    ]
