# Generated by Django 6.0 on 2025-12-14 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_food_dailynutritionsummary_dogprofile_meal_mealitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claude_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Anthropic Claude API key for document parsing",
                        max_length=200,
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI API key (alternative for document parsing)",
                        max_length=200,
                    ),
                ),
                (
                    "enable_ai_parsing",
                    models.BooleanField(
                        default=False,
                        help_text="Enable AI-powered parsing of medical documents",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AddField(
            model_name="cbpiassessment",
            name="source",
            field=models.CharField(
                choices=[("home", "At Home"), ("clinic", "Vet Clinic")],
                default="home",
                help_text="Where this assessment was completed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="corqassessment",
            name="source",
            field=models.CharField(
                choices=[("home", "At Home"), ("clinic", "Vet Clinic")],
                default="home",
                help_text="Where this assessment was completed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lymphnodemeasurement",
            name="source",
            field=models.CharField(
                choices=[("home", "At Home"), ("clinic", "Vet Clinic")],
                default="home",
                help_text="Where this measurement was taken",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="source",
            field=models.CharField(
                choices=[("home", "At Home"), ("clinic", "Vet Clinic")],
                default="clinic",
                help_text="Where this treatment was administered",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vcogctcaeevent",
            name="source",
            field=models.CharField(
                choices=[("home", "At Home"), ("clinic", "Vet Clinic")],
                default="home",
                help_text="Where this event was observed/reported",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the test/report")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("bloodwork", "Blood Work / CBC"),
                            ("chemistry", "Chemistry Panel"),
                            ("cytology", "Cytology Report"),
                            ("histopath", "Histopathology"),
                            ("imaging", "Imaging (X-ray, Ultrasound, CT)"),
                            ("urinalysis", "Urinalysis"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of this record",
                        max_length=200,
                    ),
                ),
                ("file", models.FileField(upload_to="medical_records/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="File extension (pdf, jpg, png)",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("home", "At Home"), ("clinic", "Vet Clinic")],
                        default="clinic",
                        help_text="Where this record came from",
                        max_length=10,
                    ),
                ),
                ("clinic_name", models.CharField(blank=True, max_length=200)),
                ("veterinarian", models.CharField(blank=True, max_length=200)),
                (
                    "ai_parsed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether AI has attempted to parse this document",
                    ),
                ),
                (
                    "ai_extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Raw text extracted by AI from the document",
                    ),
                ),
                ("ai_parsed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "ordering": ["-date", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LabValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_name",
                    models.CharField(
                        choices=[
                            ("wbc", "WBC (White Blood Cells)"),
                            ("rbc", "RBC (Red Blood Cells)"),
                            ("hgb", "Hemoglobin"),
                            ("hct", "Hematocrit"),
                            ("plt", "Platelets"),
                            ("neutrophils", "Neutrophils"),
                            ("lymphocytes", "Lymphocytes"),
                            ("monocytes", "Monocytes"),
                            ("eosinophils", "Eosinophils"),
                            ("basophils", "Basophils"),
                            ("bun", "BUN (Blood Urea Nitrogen)"),
                            ("creatinine", "Creatinine"),
                            ("glucose", "Glucose"),
                            ("alt", "ALT (Liver enzyme)"),
                            ("alp", "ALP (Alkaline Phosphatase)"),
                            ("ast", "AST"),
                            ("albumin", "Albumin"),
                            ("total_protein", "Total Protein"),
                            ("globulin", "Globulin"),
                            ("bilirubin", "Bilirubin"),
                            ("cholesterol", "Cholesterol"),
                            ("calcium", "Calcium"),
                            ("phosphorus", "Phosphorus"),
                            ("sodium", "Sodium"),
                            ("potassium", "Potassium"),
                            ("chloride", "Chloride"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "custom_test_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom test name if 'Other' selected",
                        max_length=100,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (e.g., K/uL, g/dL, mg/dL)",
                        max_length=30,
                    ),
                ),
                (
                    "reference_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Low end of normal reference range",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "reference_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="High end of normal reference range",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_abnormal", models.BooleanField(default=False)),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False, help_text="Critically high or low value"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("home", "At Home"), ("clinic", "Vet Clinic")],
                        default="clinic",
                        max_length=10,
                    ),
                ),
                (
                    "ai_extracted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this value was extracted by AI",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_values",
                        to="health.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Value",
                "verbose_name_plural": "Lab Values",
                "ordering": ["-date", "test_name"],
            },
        ),
    ]
