# Generated by Django 6.0 on 2025-12-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0005_alter_dailyentry_appetite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Vet name or clinic name", max_length=200
                    ),
                ),
                ("clinic_name", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Oncologist, Cytologist, General Practice",
                        max_length=100,
                    ),
                ),
                (
                    "credentials",
                    models.TextField(
                        blank=True,
                        help_text="Education, certifications, qualifications",
                    ),
                ),
                (
                    "trust_rating",
                    models.IntegerField(
                        choices=[
                            (5, "Excellent - Highly Trusted"),
                            (4, "Good - Trusted"),
                            (3, "Neutral"),
                            (2, "Concerns - Use with Caution"),
                            (1, "Avoid - Serious Issues"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "issues",
                    models.TextField(
                        blank=True,
                        help_text="Document any problems or concerns with this provider",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-trust_rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("vet_visit", "Vet Visit"),
                            ("lab_result", "Lab Result"),
                            ("imaging", "Imaging (X-ray, Ultrasound, etc.)"),
                            ("procedure", "Procedure (FNA, Biopsy, etc.)"),
                            ("treatment", "Treatment Session"),
                            ("medication", "Medication Change"),
                            ("symptom", "Symptom/Observation"),
                            ("communication", "Communication (Email, Call)"),
                            ("milestone", "Milestone"),
                            ("concern", "Concern/Issue"),
                            ("research", "Research/Information"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "content",
                    models.TextField(
                        help_text="Full narrative - include all details, feelings, observations, exact communications"
                    ),
                ),
                (
                    "bruno_mood",
                    models.CharField(
                        choices=[
                            ("great", "Great - Happy, Energetic"),
                            ("good", "Good - Normal"),
                            ("okay", "Okay - Slightly Off"),
                            ("poor", "Poor - Uncomfortable"),
                            ("bad", "Bad - Distressed"),
                            ("unknown", "Unknown/Not Applicable"),
                        ],
                        default="unknown",
                        help_text="How was Bruno feeling?",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for searching",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_entries",
                        to="health.provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline Entry",
                "verbose_name_plural": "Timeline Entries",
                "ordering": ["-date", "-time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimelineAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="timeline/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image (Photo, Screenshot)"),
                            ("xray", "X-Ray"),
                            ("ultrasound", "Ultrasound"),
                            ("document", "Document (PDF, Report)"),
                            ("lab", "Lab Report"),
                            ("video", "Video"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Description of this file", max_length=200
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "timeline_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="health.timelineentry",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
