# Generated by Django 6.0 on 2025-12-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0006_provider_timelineentry_timelineattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="completed",
                help_text="Appointment status",
                max_length=12,
            ),
        ),
    ]
